#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-C50
Version  : 0.1.8
Release  : 20
URL      : https://cran.r-project.org/src/contrib/C50_0.1.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/C50_0.1.8.tar.gz
Summary  : C5.0 Decision Trees and Rule-Based Models
Group    : Development/Tools
License  : GPL-3.0
Requires: R-C50-lib = %{version}-%{release}
Requires: R-Cubist
Requires: R-partykit
BuildRequires : R-Cubist
BuildRequires : R-partykit
BuildRequires : buildreq-R

%description
recognition that extend the work of Quinlan (1993,

%package lib
Summary: lib components for the R-C50 package.
Group: Libraries

%description lib
lib components for the R-C50 package.


%prep
%setup -q -n C50
pushd ..
cp -a C50 buildavx2
popd
pushd ..
cp -a C50 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737136624

%install
export SOURCE_DATE_EPOCH=1737136624
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/C50/DESCRIPTION
/usr/lib64/R/library/C50/INDEX
/usr/lib64/R/library/C50/Meta/Rd.rds
/usr/lib64/R/library/C50/Meta/features.rds
/usr/lib64/R/library/C50/Meta/hsearch.rds
/usr/lib64/R/library/C50/Meta/links.rds
/usr/lib64/R/library/C50/Meta/nsInfo.rds
/usr/lib64/R/library/C50/Meta/package.rds
/usr/lib64/R/library/C50/Meta/vignette.rds
/usr/lib64/R/library/C50/NAMESPACE
/usr/lib64/R/library/C50/NEWS.md
/usr/lib64/R/library/C50/R/C50
/usr/lib64/R/library/C50/R/C50.rdb
/usr/lib64/R/library/C50/R/C50.rdx
/usr/lib64/R/library/C50/doc/C5.0.R
/usr/lib64/R/library/C50/doc/C5.0.Rmd
/usr/lib64/R/library/C50/doc/C5.0.html
/usr/lib64/R/library/C50/doc/Class_Probability_Calcs.R
/usr/lib64/R/library/C50/doc/Class_Probability_Calcs.Rmd
/usr/lib64/R/library/C50/doc/Class_Probability_Calcs.html
/usr/lib64/R/library/C50/doc/index.html
/usr/lib64/R/library/C50/help/AnIndex
/usr/lib64/R/library/C50/help/C50.rdb
/usr/lib64/R/library/C50/help/C50.rdx
/usr/lib64/R/library/C50/help/aliases.rds
/usr/lib64/R/library/C50/help/paths.rds
/usr/lib64/R/library/C50/html/00Index.html
/usr/lib64/R/library/C50/html/R.css
/usr/lib64/R/library/C50/tests/testthat.R
/usr/lib64/R/library/C50/tests/testthat/_snaps/basic-execution.md
/usr/lib64/R/library/C50/tests/testthat/test-basic-execution.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/C50/libs/C50.so
/V4/usr/lib64/R/library/C50/libs/C50.so
/usr/lib64/R/library/C50/libs/C50.so
